### ISSUE TITLE
I am new to node.js but it gives me error when I run

### ISSUE THREAD

**Issue by newmrxu** [FaztWeb/express-mongodb-crud#1]
`SyntaxError: Unexpected identifier in /volume1/web/mongocrud/views/index.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/volume1/web/mongocrud/node_modules/ejs/lib/ejs.js:661:12)
    at Object.compile (/volume1/web/mongocrud/node_modules/ejs/lib/ejs.js:396:16)
    at handleCache (/volume1/web/mongocrud/node_modules/ejs/lib/ejs.js:233:18)
    at tryHandleCache (/volume1/web/mongocrud/node_modules/ejs/lib/ejs.js:272:16)
    at View.exports.renderFile [as engine] (/volume1/web/mongocrud/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/volume1/web/mongocrud/node_modules/express/lib/view.js:135:8)
    at tryRender (/volume1/web/mongocrud/node_modules/express/lib/application.js:640:10)
    at Function.render (/volume1/web/mongocrud/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/volume1/web/mongocrud/node_modules/express/lib/response.js:1012:7)
    at router.get (/volume1/web/mongocrud/routes/index.js:7:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

can you please help me?

**Comment by pasteljoc** [comment]
which ejs version are you using? new 3.x version has a different syntax compared with the one used in this repo. Check changing from "<% include partials/_header %>" to "<% include('partials/_header') %>"
